### ISSUE TITLE
How to run it in windows machine

### ISSUE THREAD

**Issue by debajitsaikia** [Corteks-team/mysql_data_generator#17]
Let me know how to run the second step in windows machine
mysqldatagen --db mysql://user:password@127.0.0.1:3306/database

**Comment by Raphael67** [comment]
Hi @debajitsaikia. So you did already analyze your database with the `-a` option. You should have a setting folder created with a json in it representing your current schema. Running the command you provided should fill up your database with a default setup. What exact problem do you have on windows ? Do you have a MySQL client installed on your computer ?

**Comment by debajitsaikia** [comment]
After running the first step 
npx @corteks/mysql-data-generator --db mysql://user:password@127.0.0.1:3306/database --analyse --schema schema
I can see schema.json and schema_custom.jsonc gets generated inside settings folder.

Next I am trying to run mysqldatagen --db mysql://user:password@127.0.0.1:3306/database, I got the below error

D:\database\mysql_data_generator-master\mysql_data_generator-master>mysqldatagen --db mysql://user:password@127.0.0.1:3306/iam
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '../lib/main'
Require stack:
- D:\database\mysql_data_generator-master\mysql_data_generator-master\bin\mysqldatagen
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:667:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:887:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:74:18)←[39m
    at Object.<anonymous> (D:\database\mysql_data_generator-master\mysql_data_generator-master\bin\mysqldatagen:3:1)
←[90m    at Module._compile (internal/modules/cjs/loader.js:999:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:863:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:708:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [
    ←[32m'D:\\database\\mysql_data_generator-master\\mysql_data_generator-master\\bin\\mysqldatagen'←[39m
  ]
}

**Comment by Raphael67** [comment]
Weird that the first step is working but not the second. Do you also run it with npx ?

`npx @corteks/mysql-data-generator --db mysql://user:password@127.0.0.1:3306/database --schema schema`
